FROM node:20.18.0-alpine

ENV VERSION 0.1.0
ARG NEXT_PUBLIC_WS_URL=ws://127.0.0.1:3001
ARG NEXT_PUBLIC_API_URL=http://127.0.0.1:3001/api
ENV NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL}
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}

WORKDIR /app

COPY neosearch_frontend .

# move to neosearch-frontend directory
WORKDIR /app/neosearch_frontend

# Install dependencies
RUN npm install

# Expose port for networking
EXPOSE 3000

# run the frontend
CMD ["npm", "start"]
