FROM python:3.11

ENV VERSION 0.1.2

WORKDIR /app

COPY neosearch_crawler .

# move to the neosearch_crawler directory
WORKDIR /app/neosearch_crawler

RUN pip install poetry
RUN sh export_requirements_txt_from_poetry.sh
RUN pip uninstall -y poetry

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# run the crawler
RUN ray start --head
CMD ["python", "main.py"]

# Expose port for networking
EXPOSE 8265
