FROM python:3

ENV VERSION 0.1.0

WORKDIR /app

COPY neosearch .

# move to neosearch directory
WORKDIR /app/neosearch

RUN pip install poetry
RUN sh export_requirements_txt_from_poetry.sh
RUN pip uninstall -y poetry

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose port for networking
EXPOSE 8000
