FROM python:3

ENV VERSION 0.1.0

WORKDIR /app

COPY neosearch_frontend .

# move to neosearch-frontend directory
WORKDIR /app/neosearch_frontend

# Install dependencies
RUN npm install

# Expose port for networking
EXPOSE 3000

# run the frontend
CMD ["npm", "start"]
