# This is a Docker Compose file for setting up the neosearch-stack environment.

name: neosearch-stack
services:
  neosearch:
    build:
      context: . # The build context is the current directory
      dockerfile: Dockerfile.frontend
    command: npm run dev
    env_file: neosearch_frontend/.env
    ports:
      - '3000:3000' # Maps port 3000 on the host to port 3000 in the container.
    depends_on:
      - redis
      - searxng

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  searxng:
    image: searxng/searxng
    ports:
      - '${SEARXNG_PORT:-8080}:8080'
    volumes:
      - ./searxng/limiter.toml:/etc/searxng/limiter.toml
      - ./searxng/settings.yml:/etc/searxng/settings.yml
      - searxng_data:/data

volumes:
  redis_data:
  searxng_data:
