import { Mails } from "lucide-react";
import { FC } from "react";

export const Footer: FC = () => {
  return (
    <div className="text-center flex flex-col items-center text-xs text-zinc-700 gap-1">
      <div className="text-zinc-400">
        Answer generated by large language models, plz double check for
        correctness.
      </div>
      <div className="text-zinc-400">
        LLM, Vector DB, and other components for AI powered search.
      </div>
      <div className="flex gap-2 justify-center">
        <div>
          <a
            className="text-blue-500 font-medium inline-flex gap-1 items-center flex-nowrap text-nowrap"
            href="mailto:neos960518@gmail.com"
          >
            <Mails size={8} />
            Talk to us
          </a>
        </div>
        <div>if you need a performant and scalable AI Search!</div>
      </div>

      <div className="flex items-center justify-center flex-wrap gap-x-4 gap-y-2 mt-2 text-zinc-400">
        <a className="hover:text-zinc-950" href="https://github.com/NEOS-AI/">
          NEOS-AI
        </a>
        <a
          className="hover:text-zinc-950"
          href="https://github.com/NEOS-AI/NEOS"
        >
          NEOS
        </a>
        <a
          className="hover:text-zinc-950"
          href="https://github.com/NEOS-AI/Neosearch"
        >
          Neosearch
        </a>
        <a className="hover:text-zinc-950" href="https://github.com/NEOS-AI/neostract">
          neostract
        </a>
        <a className="hover:text-zinc-950" href="https://github.com/YeonwooSung">
          GitHub
        </a>
      </div>
    </div>
  );
};
