[tool]
[tool.poetry]
name = "neosearch"
version = "0.1.7"
description = ""
authors = [ "Yeonwoo Sung <neos960518@gmail.com>" ]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
fastapi = "^0.108.0"
python-dotenv = "^1.0.0"
llama-index = "^0.10.7"
llama-index-vector-stores-milvus = "^0.1.4"
llama-index-llms-ollama = "^0.1.2"
pyyaml = "^6.0.1"
llama-index-embeddings-huggingface = "^0.1.4"
llama-index-llms-llama-cpp = "^0.1.3"
llama-index-vector-stores-pgvecto-rs = "^0.1.2"
pgvecto-rs = {extras = ["sdk"], version = "^0.1.4"}
llama-index-retrievers-bm25 = "^0.1.3"
sentence-transformers = "^2.5.1"
ray = {extras = ["serve"], version = "^2.9.3"}
slowapi = "^0.1.9"
traceloop-sdk = "^0.14.5"

[tool.poetry.dependencies.uvicorn]
extras = [ "standard" ]
version = "^0.23.2"

[tool.poetry.dependencies.llama-index-vector-stores-postgres]
version = "^0.1.1"

[tool.poetry.dependencies.llama-index-vector-stores-pinecone]
version = "^0.1.3"

[tool.poetry.dependencies.docx2txt]
version = "^0.8"

[build-system]
requires = [ "poetry-core" ]
build-backend = "poetry.core.masonry.api"
