# logging.py
LOG_DEFAULT_LOG_NAME = "neosearch"
LOG_DEFAULT_LOG_LEVEL = "DEBUG"
LOG_DEFAULT_CONSOLE_LOG_LEVEL = "WARNING"
LOG_DEFAULT_MAX_BYTES = 10485760
LOG_DEFAULT_BACKUP_COUNT = 10
LOG_DEFAULT_LOGGING_WORKERS = 1
