// import { Mails } from "lucide-react";
import { FC } from "react";
import FooterMailMe from "@/app/components/ui/footer/footer-mailme";


export const Footer: FC = () => {
  return (
    <div className="text-center flex flex-col items-center text-xs text-zinc-700 gap-1">
      <div className="text-zinc-400">
        Answer generated by large language models, plz double check for
        correctness.
      </div>
      <div className="text-zinc-400">
        LLM, Vector DB, and other components for AI powered search.
      </div>
      {<FooterMailMe mailHref="mailto:neos960518@gmail.com" />}

      <div className="flex items-center justify-center flex-wrap gap-x-4 gap-y-2 mt-2 text-zinc-400">
        <a className="hover:text-zinc-950" href="https://github.com/NEOS-AI/">
          NEOS-AI
        </a>
        <a
          className="hover:text-zinc-950"
          href="https://github.com/NEOS-AI/neos"
        >
          NEOS
        </a>
        <a
          className="hover:text-zinc-950"
          href="https://github.com/NEOS-AI/Neosearch"
        >
          Neosearch
        </a>
        <a className="hover:text-zinc-950" href="https://github.com/NEOS-AI/go4search">
          go4search
        </a>
        <a className="hover:text-zinc-950" href="https://github.com/YeonwooSung">
          GitHub
        </a>
      </div>
    </div>
  );
};
